### PR TITLE
firewall changes

### PR DESCRIPTION
**Pull request by nean-and-i**
please consider to disable firewall per default

### CODE REVIEW

**Comment by kingosticks** [comment]
I think extra security should be opt-out. For the same reason ssh is disabled by default.

**Comment by nean-and-i** [comment]
that's all up to you guys, the maintainers.
however, please deliver prober rules to get at least main services functional ootb, like airplay,...

**Comment by kingosticks** [comment]
I have access to one apple device to test with (an ipad) and it works out of the box with that. Perhaps it's running old software, it's not mine so I can't do much about that.  I rely on helpful people like yourself to test the release candidates with a wider range of hardware. It might not be the best situation but it is realistic. I will look at some kind of free 3rd party airplay sender software, that may or may not have caught this issue but it can't hurt.

**Comment by kingosticks** [comment]
I'm a bit surprised about those extra tcp ports being required, the ones I specified were based on the shairport-sync config. If it's using different ones then maybe thats their bug.

**Comment by nean-and-i** [comment]
I have a few apple devices with different ios/macos versions, unfortunately none of them (iphone7/ipad2/hackintosh) worked ootb.
I disabled the firewall and it worked (caution: DROP default rule) .
Than I moved on with step-by-step debugging by checking which ports are open and which services are listening.
Next I implemented a logging rule at the end, just to check what else is being blocked. One thing I recognized is, that incoming responses of a previous broadcasts are being blocked, and dhcpclient communication as well,...
It would be cool, if relevant ports are getting unblocked after the service has been enabled via webgui, it seems in case of airplay some ports are missing.

I really question the need of a firewall on such a box, because unblocked services could be vulnerable anyway, so any sort of a clever upgrade concept (eg. OTA) could make more sense in terms of security.
please note that no ipv6 rules are in place, while ipv6 is enabled by default.

I recommend wifi password (psk) should be stored non-plaintext in wpa.conf (wpa_passphrase)

**Comment by ReckeDJ** [comment]
This 'fix' does not work for me. Even when disabling iptables at all, shairport-sync is not working on musicbox-start. After doing a 'service shairport-sync restart' it works directly. So not a firewall issue. I tried to log the startup to find out why the shairport-sync does not work but cannot figure it out.

**Comment by nean-and-i** [comment]
have you tried to switch the tables to default ACCEPT when disabling firewall?

``
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -F
iptables -X
iptables -L -vn
``

**Comment by kingosticks** [comment]
This is all very helpful, thanks for taking the time to investigate this, I really appreciate that.

* The missing DHCP ports is a big screw up. Might as well sort that properly and open ports 67 and 68. Presumably it only works at all because the firewall is configured after the IP address is obtained.
* `UDP 5678` - ????
* `UDP 36996` - ????
* `UDP 51689` - Xsan. Xsan Filesystem Access (Apple). [Don't know why we want this](https://en.wikipedia.org/wiki/Xsan)
* `UDP 1900` - UPnP - sounds sensible, I think we used to have this.
* `TCP 5000-5005` - Shairport-sync listens on TCP 5000 [as per the config](https://github.com/pimusicbox/pimusicbox/blob/develop/filechanges/etc/shairport-sync.conf#L19)
* `TCP 38888`-  ????
* `TCP 49014` - ????
* `TCP 45962` - ????
* `TCP 49152` - Xsan. Xsan Filesystem Access (Apple). As above
* `TCP 56278` - ????
* `UDP 6000:6005` - 6001:6003 very deliberately matches our [shairport-sync config](https://github.com/pimusicbox/pimusicbox/blob/develop/filechanges/etc/shairport-sync.conf#L21). However, there might be an [off-by-one error](https://github.com/mikebrady/shairport-sync/blob/master/rtp.c#L596) and I've opened an issue there for that. However, we might as well just keep the default config (`udp_port_range = 100`), open 6001:6100/6101 and not worry about this.
* `UDP 60458` - Xsan. Xsan Filesystem Access (Apple). As above

I don't see which of these were breaking Airplay support (unless it was related to ports 600x) and I'm reluctant to add a bunch of random ports that I do not understand. I'm curious to know what was using those random high ports.

Sure, any of the allowed services could be vulnerable but it's still fewer points of entry; I don't think that's a good argument for removing it. The fact that any additional services you might install will probably require you to mess around with all this isn't great from a usability standpoint. At least now having the ability to easily disable the whole thing makes debugging it easier; or one can *actively* choose to disable the firewall if they want to. 

My v1.0 work uses ufw to handle the ipv6 side of things. I don't really want to have to mess around with that separately, maybe we should just turn it off? `net.ipv6.conf.all.disable_ipv6 = 1` ?

I don't think we've ever looked into wpa_passphrase, that's interesting. I guess we could convert their plaintext password into a passphrase and then replace the wifi password value in settings.ini with that. Then we can keep the same logic. That sounds good.

**Comment by nean-and-i** [comment]
That seems to be generic description of the ports, hard to tell if proprietary stuff really needs it, and if it is version related. also, could well be that other apple services try to connect to it, nowadays even os'es are chatty,...

my personal view on this is: it's a cool media box and I'd see it in private lan's which are mostly secured via NAT or firewall from outside, so it can have firewall disabled.
maybe you can implement a switch for privat/public use that triggers corresponding firewall rules.

if you need to secure the box, pls. think of a good security concept.
I'd suggest:
- disable IPv6 , if not possible, force it to link-local only
- run it as user and chroot environment (disable root)
- secure any privacy and abusable information
- no cleartext passwords,.. (3rd party account such as spotify,  wifi-password, etc,..) so, in case the box gets hijacked the information is useless

thanks for your effort and cooperation!

**Comment by nean-and-i** [comment]
without airplay client connected:

```
root@MusicBox:~# netstat -tulpena
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          9865        2959/dropbear
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      0          9855        2946/smbd
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      0          10124       2980/shairport-sync
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      0          9857        2946/smbd
tcp        0    368 192.168.1.33:22         192.168.1.50:55427      ESTABLISHED 0          10150       2996/dropbear
tcp6       0      0 :::22                   :::*                    LISTEN      0          9866        2959/dropbear
tcp6       0      0 :::445                  :::*                    LISTEN      0          9851        2946/smbd
tcp6       0      0 :::5000                 :::*                    LISTEN      0          10125       2980/shairport-sync
tcp6       0      0 :::139                  :::*                    LISTEN      0          9853        2946/smbd
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           106        9039        2312/avahi-daemon:
udp        0      0 0.0.0.0:32808           0.0.0.0:*                           0          9680        2902/dhclient
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          9699        2902/dhclient
udp        0      0 0.0.0.0:38736           0.0.0.0:*                           106        9041        2312/avahi-daemon:
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          10363       3004/ntpdate
udp        0      0 192.168.1.255:137       0.0.0.0:*                           0          9794        2937/nmbd
udp        0      0 192.168.1.33:137        0.0.0.0:*                           0          9793        2937/nmbd
udp        0      0 0.0.0.0:137             0.0.0.0:*                           0          9790        2937/nmbd
udp        0      0 192.168.1.255:138       0.0.0.0:*                           0          9796        2937/nmbd
udp        0      0 192.168.1.33:138        0.0.0.0:*                           0          9795        2937/nmbd
udp        0      0 0.0.0.0:138             0.0.0.0:*                           0          9791        2937/nmbd
udp6       0      0 :::60854                :::*                                106        9042        2312/avahi-daemon:
udp6       0      0 :::5353                 :::*                                106        9040        2312/avahi-daemon:
udp6       0      0 :::14690                :::*                                0          9681        2902/dhclient
udp6       0      0 :::123                  :::*                                0          10364       3004/ntpdate
```



with airplay client connected:


```
root@MusicBox:~# netstat -tulpena
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          9865        2959/dropbear
tcp        0      0 0.0.0.0:6680            0.0.0.0:*               LISTEN      1001       11153       3055/python
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      0          9855        2946/smbd
tcp        0      0 192.168.1.33:49152      0.0.0.0:*               LISTEN      108        11165       2970/upmpdcli
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      0          10124       2980/shairport-sync
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      0          9857        2946/smbd
tcp        0    780 192.168.1.33:43124      193.235.232.87:4070     ESTABLISHED 1001       11114       3055/python
tcp        0    268 192.168.1.33:22         192.168.1.50:55427      ESTABLISHED 0          10150       2996/dropbear
tcp        0      0 127.0.0.1:46984         127.0.0.1:6600          ESTABLISHED 108        11160       2970/upmpdcli
tcp        0      0 192.168.1.33:5000       192.168.1.50:55521      ESTABLISHED 0          10961       2980/shairport-sync
tcp        0      0 192.168.1.33:47812      2.16.194.217:80         ESTABLISHED 1001       11117       3055/python
tcp6       0      0 :::22                   :::*                    LISTEN      0          9866        2959/dropbear
tcp6       0      0 :::445                  :::*                    LISTEN      0          9851        2946/smbd
tcp6       0      0 :::49152                :::*                    LISTEN      108        11166       2970/upmpdcli
tcp6       0      0 0.0.0.0:6600            :::*                    LISTEN      1001       11149       3055/python
tcp6       0      0 :::5000                 :::*                    LISTEN      0          10125       2980/shairport-sync
tcp6       0      0 :::139                  :::*                    LISTEN      0          9853        2946/smbd
tcp6       0      0 127.0.0.1:6600          127.0.0.1:46984         ESTABLISHED 1001       11161       3055/python
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           106        9039        2312/avahi-daemon:
udp        0      0 0.0.0.0:32808           0.0.0.0:*                           0          9680        2902/dhclient
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          9699        2902/dhclient
udp        0      0 0.0.0.0:38736           0.0.0.0:*                           106        9041        2312/avahi-daemon:
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           108        11169       2970/upmpdcli
udp        0      0 192.168.1.33:6001       0.0.0.0:*                           0          10964       2980/shairport-sync
udp        0      0 192.168.1.33:6002       0.0.0.0:*                           0          10965       2980/shairport-sync
udp        0      0 192.168.1.33:6003       0.0.0.0:*                           0          10966       2980/shairport-sync
udp        0      0 127.0.0.1:56199         0.0.0.0:*                           108        11167       2970/upmpdcli
udp        0      0 192.168.1.255:137       0.0.0.0:*                           0          9794        2937/nmbd
udp        0      0 192.168.1.33:137        0.0.0.0:*                           0          9793        2937/nmbd
udp        0      0 0.0.0.0:137             0.0.0.0:*                           0          9790        2937/nmbd
udp        0      0 192.168.1.255:138       0.0.0.0:*                           0          9796        2937/nmbd
udp        0      0 192.168.1.33:138        0.0.0.0:*                           0          9795        2937/nmbd
udp        0      0 0.0.0.0:138             0.0.0.0:*                           0          9791        2937/nmbd
udp6       0      0 :::60854                :::*                                106        9042        2312/avahi-daemon:
udp6       0      0 :::5353                 :::*                                106        9040        2312/avahi-daemon:
udp6       0      0 :::14690                :::*                                0          9681        2902/dhclient
```

install lsof:
`apt-get install lsof`

list all network ports:
```
root@MusicBox:~# lsof -i
COMMAND    PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
avahi-dae 2312    avahi   13u  IPv4   9039      0t0  UDP *:mdns
avahi-dae 2312    avahi   14u  IPv6   9040      0t0  UDP *:mdns
avahi-dae 2312    avahi   15u  IPv4   9041      0t0  UDP *:38736
avahi-dae 2312    avahi   16u  IPv6   9042      0t0  UDP *:60854
dhclient  2902     root    7u  IPv4   9699      0t0  UDP *:bootpc
dhclient  2902     root   20u  IPv4   9680      0t0  UDP *:32808
dhclient  2902     root   21u  IPv6   9681      0t0  UDP *:14690
nmbd      2937     root    9u  IPv4   9790      0t0  UDP *:netbios-ns
nmbd      2937     root   10u  IPv4   9791      0t0  UDP *:netbios-dgm
nmbd      2937     root   11u  IPv4   9793      0t0  UDP MusicBox.local:netbios-ns
nmbd      2937     root   12u  IPv4   9794      0t0  UDP 192.168.1.255:netbios-ns
nmbd      2937     root   13u  IPv4   9795      0t0  UDP MusicBox.local:netbios-dgm
nmbd      2937     root   14u  IPv4   9796      0t0  UDP 192.168.1.255:netbios-dgm
smbd      2946     root   27u  IPv6   9851      0t0  TCP *:microsoft-ds (LISTEN)
smbd      2946     root   28u  IPv6   9853      0t0  TCP *:netbios-ssn (LISTEN)
smbd      2946     root   29u  IPv4   9855      0t0  TCP *:microsoft-ds (LISTEN)
smbd      2946     root   30u  IPv4   9857      0t0  TCP *:netbios-ssn (LISTEN)
dropbear  2959     root    3u  IPv4   9865      0t0  TCP *:ssh (LISTEN)
dropbear  2959     root    4u  IPv6   9866      0t0  TCP *:ssh (LISTEN)
upmpdcli  2970 upmpdcli    5u  IPv4  11160      0t0  TCP localhost:46984->localhost:6600 (ESTABLISHED)
upmpdcli  2970 upmpdcli    6u  IPv4  11165      0t0  TCP MusicBox.local:49152 (LISTEN)
upmpdcli  2970 upmpdcli    7u  IPv6  11166      0t0  TCP *:49152 (LISTEN)
upmpdcli  2970 upmpdcli    8u  IPv4  11167      0t0  UDP localhost:56199
upmpdcli  2970 upmpdcli   10u  IPv4  11169      0t0  UDP *:1900
shairport 2980     root    4u  IPv4  10124      0t0  TCP *:5000 (LISTEN)
shairport 2980     root    5u  IPv6  10125      0t0  TCP *:5000 (LISTEN)
shairport 2980     root    9u  IPv4  10961      0t0  TCP MusicBox.local:5000->airplayclient.local:55521 (ESTABLISHED)
shairport 2980     root   10u  IPv4  10964      0t0  UDP MusicBox.local:x11-1
shairport 2980     root   11u  IPv4  10965      0t0  UDP MusicBox.local:x11-2
shairport 2980     root   12u  IPv4  10966      0t0  UDP MusicBox.local:x11-3
dropbear  2996     root    6u  IPv4  10150      0t0  TCP MusicBox.local:ssh->airplayclient.local:55427 (ESTABLISHED)
mopidy    3055   mopidy   14u  IPv4  11114      0t0  TCP MusicBox.local:43124->lon2-accesspoint-a13.lon2.spotify.com:4070 (ESTABLISHED)
mopidy    3055   mopidy   15u  IPv4  11117      0t0  TCP MusicBox.local:47812->a2-16-194-217.deploy.akamaitechnologies.com:http (ESTABLISHED)
mopidy    3055   mopidy   17u  IPv6  11149      0t0  TCP *:6600 (LISTEN)
mopidy    3055   mopidy   18u  IPv4  11153      0t0  TCP *:6680 (LISTEN)
mopidy    3055   mopidy   26u  IPv6  11161      0t0  TCP localhost:6600->localhost:46984 (ESTABLISHED)

```

**Comment by kingosticks** [comment]
From all those it looks like just the following are wrong/missing:
* UDP 1900 (upmpdcli)
* UDP 67 & 68 (dhclient)

Which still doesn't explain what was breaking shairport-sync! I've spent some time looking through the shairport-sync code and it seems pretty clear that it's only 5000 TCP and then 3 per client (starting from UDP 6001) that are used. Avahi is already open (UDP 5353) but I don't know what avahi is doing with 38736. So I'm really confused, and I'm leaning towards having the firewall disabled by default. Raspbian doesn't include one, presumably because it just gets in the way more than helps.  Life is too short!

**Pull request closed without merging**
