### PR TITLE
Update create_musicbox.sh

### PR DESCRIPTION
**Pull request by jpswade**
Fix the "Extra junk after value" issue

### CODE REVIEW

**Comment by kingosticks** [comment]
You've lost me.

**Comment by jpswade** [comment]
`echo -e` causes the `E: Extra junk after value` error in apt-get, while `printf` does not. It's really that simple.

**Comment by kingosticks** [comment]
OK, thanks for the explanation. I guess it's the extra newline that echo so kindly inserts.

**Comment by jodal** [comment]
`echo -n` does the same.

**Pull request merged**
