### PR TITLE
Support boomberry-digi, boomberry-dac and phatdac cards.

### PR DESCRIPTION
**Pull request by kingosticks**

### CODE REVIEW

**Comment by kingosticks** [comment]
@francesco-vannini @shawaj I've no way of testing this, I guessed based on the module code... If you can verify the justboom ones (I have a phatdac) then that'd be helpful.

**Comment by kingosticks** [comment]
The big problem with this is that the latest Wheezy kernel is 4.1.19-v7+. 
```
# ls -l /lib/modules/4.1.19-v7+/kernel/sound/soc/bcm/
total 96
-rw-r--r-- 1 root root 15524 Mar 14  2016 snd-soc-bcm2708-i2s.ko
-rw-r--r-- 1 root root  7456 Mar 14  2016 snd-soc-hifiberry-amp.ko
-rw-r--r-- 1 root root  7652 Mar 14  2016 snd-soc-hifiberry-dac.ko
-rw-r--r-- 1 root root 10892 Mar 14  2016 snd-soc-hifiberry-dacplus.ko
-rw-r--r-- 1 root root  9616 Mar 14  2016 snd-soc-hifiberry-digi.ko
-rw-r--r-- 1 root root  8252 Mar 14  2016 snd-soc-iqaudio-dac.ko
-rw-r--r-- 1 root root  9608 Mar 14  2016 snd-soc-raspidac3.ko
-rw-r--r-- 1 root root  7316 Mar 14  2016 snd-soc-rpi-dac.ko
-rw-r--r-- 1 root root  7988 Mar 14  2016 snd-soc-rpi-proto.ko
```

**Comment by kingosticks** [comment]
And that's because the 4.4.x kernels removed support for booting *without* a Device Tree. This finally makes sense. If I (finally) enable Device Tree Overlays and fix all that up we'll be golden. This will also fix https://github.com/pimusicbox/pimusicbox/issues/393

**Comment by shawaj** [comment]
@kingosticks no problem - we can test it no problem. Is this in a RC image?

**Comment by kingosticks** [comment]
This is already in RC4 and so far no complaints...

**Pull request closed without merging**
